version: '3.8'

services:
  proxy:
    build: proxy
    container_name: proxy
    volumes:
      - "./hugo/content:/app/static"
    ports:
      - "8080:8080"
    networks:
      - mylocal
    depends_on:
      - server
  server:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    command: server
    entrypoint: hugo
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    networks:
      - mylocal
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mylocal
networks:
  mylocal:
    driver: bridge
