// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/protoc/user.proto

package user

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsererClient is the client API for Userer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsererClient interface {
	Profile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	CheckUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error)
	Create(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type usererClient struct {
	cc grpc.ClientConnInterface
}

func NewUsererClient(cc grpc.ClientConnInterface) UsererClient {
	return &usererClient{cc}
}

func (c *usererClient) Profile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/geo_provider.Userer/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usererClient) CheckUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/geo_provider.Userer/CheckUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usererClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/geo_provider.Userer/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usererClient) Create(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/geo_provider.Userer/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsererServer is the server API for Userer service.
// All implementations must embed UnimplementedUsererServer
// for forward compatibility
type UsererServer interface {
	Profile(context.Context, *ProfileRequest) (*ProfileResponse, error)
	CheckUser(context.Context, *UserRequest) (*empty.Empty, error)
	List(context.Context, *empty.Empty) (*ListResponse, error)
	Create(context.Context, *UserRequest) (*empty.Empty, error)
	mustEmbedUnimplementedUsererServer()
}

// UnimplementedUsererServer must be embedded to have forward compatible implementations.
type UnimplementedUsererServer struct {
}

func (UnimplementedUsererServer) Profile(context.Context, *ProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedUsererServer) CheckUser(context.Context, *UserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUser not implemented")
}
func (UnimplementedUsererServer) List(context.Context, *empty.Empty) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedUsererServer) Create(context.Context, *UserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUsererServer) mustEmbedUnimplementedUsererServer() {}

// UnsafeUsererServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsererServer will
// result in compilation errors.
type UnsafeUsererServer interface {
	mustEmbedUnimplementedUsererServer()
}

func RegisterUsererServer(s grpc.ServiceRegistrar, srv UsererServer) {
	s.RegisterService(&Userer_ServiceDesc, srv)
}

func _Userer_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsererServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geo_provider.Userer/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsererServer).Profile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userer_CheckUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsererServer).CheckUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geo_provider.Userer/CheckUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsererServer).CheckUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userer_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsererServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geo_provider.Userer/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsererServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userer_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsererServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geo_provider.Userer/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsererServer).Create(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Userer_ServiceDesc is the grpc.ServiceDesc for Userer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Userer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geo_provider.Userer",
	HandlerType: (*UsererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Profile",
			Handler:    _Userer_Profile_Handler,
		},
		{
			MethodName: "CheckUser",
			Handler:    _Userer_CheckUser_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Userer_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Userer_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protoc/user.proto",
}
