version: '3.8'

services:
  user:
    build: .
    container_name: user
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    networks:
      - rabbitmq_mylocal
      - mylocal
    depends_on:
      - dbuser
  dbuser:
    container_name: dbuser
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
#    volumes:
#      - ./.database/postgres/data:/var/lib/postgresql/data
    networks:
      - mylocal
networks:
  mylocal:
    driver: bridge
  rabbitmq_mylocal:
    external: true
